"""PDF Report Generator Service.

Sprint 14: Professional PDF generation for compliance reports.

Uses ReportLab for PDF generation with:
- Professional formatting and styling
- VIBOTAJ branding
- Tables for structured data
- Proper document structure
"""

import io
from datetime import datetime
from typing import Dict, Any, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, ListFlowable, ListItem
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


# VIBOTAJ brand colors
VIBOTAJ_PRIMARY = colors.HexColor("#1a365d")  # Dark blue
VIBOTAJ_SECONDARY = colors.HexColor("#2c5282")  # Medium blue
VIBOTAJ_ACCENT = colors.HexColor("#38a169")  # Green (for compliance)
VIBOTAJ_WARNING = colors.HexColor("#d69e2e")  # Yellow/orange
VIBOTAJ_DANGER = colors.HexColor("#e53e3e")  # Red


def generate_eudr_compliance_report(report: Dict[str, Any]) -> bytes:
    """Generate PDF version of EUDR compliance report.

    Args:
        report: Dictionary containing EUDR compliance data

    Returns:
        PDF file as bytes
    """
    buffer = io.BytesIO()

    # Create PDF document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.5*cm,
        leftMargin=1.5*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    # Get styles
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=VIBOTAJ_PRIMARY,
        alignment=TA_CENTER,
        spaceAfter=20
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=VIBOTAJ_SECONDARY,
        spaceBefore=15,
        spaceAfter=10
    )

    subheading_style = ParagraphStyle(
        'SubHeading',
        parent=styles['Heading3'],
        fontSize=11,
        textColor=VIBOTAJ_SECONDARY,
        spaceBefore=10,
        spaceAfter=5
    )

    normal_style = styles['Normal']

    # Build document elements
    elements = []

    # Header
    elements.append(Paragraph("VIBOTAJ Global Nigeria Ltd", ParagraphStyle(
        'CompanyName',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.gray,
        alignment=TA_RIGHT
    )))
    elements.append(Paragraph("EU TRACES: RC1479592", ParagraphStyle(
        'Registration',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.gray,
        alignment=TA_RIGHT
    )))
    elements.append(Spacer(1, 0.5*cm))

    # Title
    elements.append(Paragraph("EUDR COMPLIANCE REPORT", title_style))
    elements.append(HRFlowable(width="100%", thickness=2, color=VIBOTAJ_PRIMARY))
    elements.append(Spacer(1, 0.3*cm))

    # Report metadata
    elements.append(Paragraph(f"Generated: {report.get('generated_at', datetime.utcnow().isoformat())}", normal_style))
    elements.append(Paragraph(f"Generated By: {report.get('generated_by', 'System')}", normal_style))
    elements.append(Paragraph(f"Report Type: {report.get('report_type', 'EUDR Compliance Report')}", normal_style))
    elements.append(Spacer(1, 0.5*cm))

    # Shipment Details
    shipment = report.get('shipment', {})
    elements.append(Paragraph("SHIPMENT DETAILS", heading_style))

    shipment_data = [
        ["Field", "Value"],
        ["Reference", shipment.get('reference', 'N/A')],
        ["Container Number", shipment.get('container_number', 'N/A')],
        ["B/L Number", shipment.get('bl_number', 'N/A')],
        ["Product Type", shipment.get('product_type', 'N/A')],
        ["HS Code", shipment.get('hs_code', 'N/A')],
        ["Destination", shipment.get('destination', 'N/A')],
    ]

    shipment_table = Table(shipment_data, colWidths=[4*cm, 10*cm])
    shipment_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), VIBOTAJ_SECONDARY),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7fafc")]),
    ]))
    elements.append(shipment_table)
    elements.append(Spacer(1, 0.5*cm))

    # Compliance Status
    compliance = report.get('compliance_status', {})
    elements.append(Paragraph("COMPLIANCE STATUS", heading_style))

    overall_status = compliance.get('overall_status', 'PENDING')
    is_compliant = compliance.get('is_compliant', False)
    risk_level = compliance.get('overall_risk_level', 'UNKNOWN')

    # Status color coding
    status_color = VIBOTAJ_ACCENT if is_compliant else VIBOTAJ_DANGER

    status_data = [
        ["Overall Status", overall_status.upper()],
        ["Compliant", "YES" if is_compliant else "NO"],
        ["Risk Level", risk_level.upper()],
    ]

    status_table = Table(status_data, colWidths=[4*cm, 10*cm])
    status_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), VIBOTAJ_SECONDARY),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
        ('TEXTCOLOR', (1, 0), (1, -1), status_color),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),
    ]))
    elements.append(status_table)
    elements.append(Spacer(1, 0.5*cm))

    # Compliance Checklist
    checklist = compliance.get('checklist', [])
    if checklist:
        elements.append(Paragraph("Compliance Checklist", subheading_style))

        checklist_data = [["Status", "Item", "Details"]]
        for item in checklist:
            status = "PASS" if item.get('passed') else "FAIL"
            checklist_data.append([
                status,
                item.get('item', ''),
                item.get('details', '')
            ])

        checklist_table = Table(checklist_data, colWidths=[2*cm, 5*cm, 7*cm])
        checklist_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), VIBOTAJ_SECONDARY),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (0, -1), 'CENTER'),
            ('ALIGN', (1, 0), (-1, -1), 'LEFT'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7fafc")]),
        ]))

        # Color code PASS/FAIL
        for i, item in enumerate(checklist, start=1):
            if item.get('passed'):
                checklist_table.setStyle(TableStyle([
                    ('TEXTCOLOR', (0, i), (0, i), VIBOTAJ_ACCENT),
                ]))
            else:
                checklist_table.setStyle(TableStyle([
                    ('TEXTCOLOR', (0, i), (0, i), VIBOTAJ_DANGER),
                ]))

        elements.append(checklist_table)
        elements.append(Spacer(1, 0.5*cm))

    # Origins (if present)
    origins = report.get('origins', [])
    if origins:
        elements.append(Paragraph("ORIGIN VERIFICATION", heading_style))

        for i, origin in enumerate(origins, start=1):
            elements.append(Paragraph(f"Origin {i}: {origin.get('farm_plot_id', 'N/A')}", subheading_style))

            origin_data = [
                ["Country", origin.get('country', 'N/A')],
                ["Region", origin.get('region', 'N/A')],
                ["Coordinates", f"Lat: {origin.get('geolocation', {}).get('lat', 'N/A')}, Lng: {origin.get('geolocation', {}).get('lng', 'N/A')}"],
                ["Cutoff Compliant", "YES" if origin.get('cutoff_compliant') else "NO"],
                ["Risk Level", origin.get('risk_assessment', {}).get('risk_level', 'N/A')],
            ]

            origin_table = Table(origin_data, colWidths=[4*cm, 10*cm])
            origin_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#edf2f7")),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ]))
            elements.append(origin_table)
            elements.append(Spacer(1, 0.3*cm))

    # Due Diligence Statement
    dds = report.get('due_diligence_statement', {})
    if dds:
        elements.append(Paragraph("DUE DILIGENCE STATEMENT", heading_style))
        elements.append(Paragraph(f"Reference: {dds.get('statement_reference', 'N/A')}", normal_style))
        elements.append(Spacer(1, 0.2*cm))

        declaration = dds.get('declaration', {})
        if declaration:
            elements.append(Paragraph(declaration.get('text', ''), ParagraphStyle(
                'Declaration',
                parent=normal_style,
                fontSize=9,
                textColor=colors.gray,
                borderPadding=(10, 10, 10, 10),
                backColor=colors.HexColor("#f7fafc"),
            )))
        elements.append(Spacer(1, 0.5*cm))

    # Legal Basis
    legal = report.get('legal_basis', {})
    if legal:
        elements.append(Paragraph("LEGAL BASIS", heading_style))

        legal_data = [
            ["Regulation", legal.get('regulation', 'N/A')],
            ["Title", legal.get('title', 'N/A')],
            ["Cutoff Date", legal.get('cutoff_date', 'N/A')],
        ]

        legal_table = Table(legal_data, colWidths=[4*cm, 10*cm])
        legal_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#edf2f7")),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ]))
        elements.append(legal_table)

    # Footer
    elements.append(Spacer(1, 1*cm))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.gray))
    elements.append(Paragraph(
        "This report was automatically generated by TraceHub - VIBOTAJ Global Nigeria Ltd compliance platform.",
        ParagraphStyle('Footer', parent=normal_style, fontSize=8, textColor=colors.gray, alignment=TA_CENTER)
    ))
    elements.append(Paragraph(
        f"Report generated on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
        ParagraphStyle('FooterDate', parent=normal_style, fontSize=8, textColor=colors.gray, alignment=TA_CENTER)
    ))

    # Build PDF
    doc.build(elements)

    # Get PDF content
    buffer.seek(0)
    return buffer.getvalue()


def generate_document_checklist_pdf(
    shipment_ref: str,
    documents: List[Dict[str, Any]],
    required_types: List[str],
    completeness: Dict[str, Any]
) -> bytes:
    """Generate PDF checklist of required vs uploaded documents.

    Args:
        shipment_ref: Shipment reference number
        documents: List of uploaded documents
        required_types: List of required document types
        completeness: Document completeness summary

    Returns:
        PDF file as bytes
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.5*cm,
        leftMargin=1.5*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("DOCUMENT CHECKLIST", ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=VIBOTAJ_PRIMARY,
        alignment=TA_CENTER
    )))
    elements.append(Paragraph(f"Shipment: {shipment_ref}", ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=12,
        alignment=TA_CENTER,
        spaceAfter=20
    )))

    # Summary
    summary_data = [
        ["Total Required", str(completeness.get('total_required', 0))],
        ["Uploaded", str(completeness.get('total_uploaded', 0))],
        ["Complete", str(completeness.get('complete', 0))],
        ["Pending Validation", str(completeness.get('pending_validation', 0))],
        ["Missing", str(len(completeness.get('missing', [])))],
    ]

    summary_table = Table(summary_data, colWidths=[5*cm, 5*cm])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), VIBOTAJ_SECONDARY),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.5*cm))

    # Document list
    if documents:
        doc_data = [["Document Type", "Status", "Uploaded"]]
        for doc in documents:
            doc_data.append([
                doc.get('document_type', 'Unknown'),
                doc.get('status', 'Unknown'),
                doc.get('uploaded_at', 'N/A')[:10] if doc.get('uploaded_at') else 'N/A'
            ])

        doc_table = Table(doc_data, colWidths=[6*cm, 4*cm, 4*cm])
        doc_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), VIBOTAJ_SECONDARY),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 1, colors.lightgrey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7fafc")]),
        ]))
        elements.append(doc_table)

    # Missing documents
    missing = completeness.get('missing', [])
    if missing:
        elements.append(Spacer(1, 0.5*cm))
        elements.append(Paragraph("MISSING DOCUMENTS", ParagraphStyle(
            'MissingTitle',
            parent=styles['Heading2'],
            fontSize=12,
            textColor=VIBOTAJ_DANGER
        )))

        for doc_type in missing:
            elements.append(Paragraph(f"• {doc_type}", styles['Normal']))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
